apiVersion: v1
kind: Secret
metadata:
  name: github-secrets
type: Opaque
stringData:
  GITHUB_APP_CLIENT_ID: ${GITHUB_APP_CLIENT_ID}
  GITHUB_APP_CLIENT_SECRET: ${GITHUB_APP_CLIENT_SECRET}
  GITHUB_APP_ID: "${GITHUB_APP_ID}"
  GITHUB_APP_WEBHOOK_URL: ${GITHUB_APP_WEBHOOK_URL}
  GITHUB_APP_WEBHOOK_SECRET: ${GITHUB_APP_WEBHOOK_SECRET}
  GITHUB_APP_PRIVATE_KEY: |
    ${GITHUB_APP_PRIVATE_KEY}
  GITHUB_ORGANIZATION: ${GITHUB_ORGANIZATION}