apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: backstage
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
          key: app-config-rhdh.yaml
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: custom-rhdh-dynamic-plugins
    extraEnvs:
      secrets:
        - name: rhdh-secrets
        - name: github-secrets
        - name: quay-token
        - name: argocd-token
      configMaps:
        - name: custom-rhdh-config
    extraFiles:
      configMaps:
        - name: kube-root-ca.crt
          key: ca.crt
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
  deployment:
    patch:
      spec:
        template:
          spec:
            automountServiceAccountToken: true