apiVersion: v1
kind: Secret
metadata:
  name: github-token
type: Opaque
stringData:
  GITHUB_TOKEN: ${GITHUB_TOKEN}
  GITHUB_APP_CLIENT_ID: ${GITHUB_APP_CLIENT_ID}
  GITHUB_APP_CLIENT_SECRET: ${GITHUB_APP_CLIENT_SECRET}
